version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_bot_finanzas
    restart: always
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    environment:
      - N8N_PORT=${N8N_PORT}
      - NODE_ENV=${NODE_ENV}
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - n8n_data:/home/node/.n8n
    command: start

volumes:
  n8n_data: